openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: /api/v1
    description: Main docs

paths:
  /companies:
    get:
      summary: Returns a list of companies.
      description: ''
      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Company'

  /companies/{companyId}:
    get:
      summary: Returns a single company by id.
      description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Company'
        '400':
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: NOT FOUND
        '500':
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      parameters:
        - name: companyId
          in: path
          required: true
          description: company Id.
          schema:
            type: string
            format: uuid
            minimum: 1

  /companies/{companyId}/payments:
    get:
      summary: Returns a bynch of payments for company employees.
      description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: NOT FOUND
        '500':
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      parameters:
        - name: companyId
          in: path
          required: true
          description: company Id.
          schema:
            type: string
            format: uuid
        - name: startDate
          in: query
          required: false
          description: start date.
          schema:
            type: string
            format: YYYY-MM
        - name: asCsv
          in: query
          required: false
          description: Export result as csv if need.
          schema:
            type: boolean

components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    Employee:
      type: object
      properties:
        id:
          type: string
        fullName:
          type: string
        companyId:
          type: string
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              msg:
                type: string
    PaymentResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            '[employeeId]':
              type: array
              items:
                type: object
                properties:
                  calculationDate:
                    type: string
                  salary:
                    type: object
                    properties:
                      date:
                        type: string
                      value:
                        type: integer
                  bonus:
                    type: object
                    properties:
                      date:
                        type: string
                      value:
                        type: integer
                  employee:
                    $ref: '#/components/schemas/Employee'
